name: grabbing streams

on:
  schedule:
    - cron: '* */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1alt"
      
      - name: Grab m3u8 files
        run: |
          cd ./core/platforms/
          python3 twitch.py livethess > ../../channel/thessalia.m3u8

      - name: Git add, commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add -A
          git commit -m "Streams updated"
          git push
