name: Update Streams

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update_streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Other steps for setting up Python and installing dependencies...

      - name: Update .m3u8 files
        run: |
          python twitch.py livethess > ../../streams/thessalia.m3u8
          # Add more channels as needed

      - name: Configure Git
        run: |
          git config --global user.email "<your-email>"
          git config --global user.name "GitHub Actions"

      - name: Move .m3u8 files to public repository
        run: |
          mkdir -p ../channels
          cp ../../streams/*.m3u8 ../channels/

      - name: Commit and push changes
        run: |
          cd ../channels
          git init
          git add .
          git commit -m "Update .m3u8 files"
          git push --force --quiet "https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/med1altd/channels.git" main
