name: Update Streams

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  update_streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Assuming you want to use Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install requests module if needed
      - name: Install requests module
        run: pip install requests

      # Download twitch.py from GitHub
      - name: Download twitch.py
        run: curl -o twitch.py -L https://github.com/med1altd/streams/raw/main/core/platforms/twitch.py

      # Make sure twitch.py has executable permissions
      - name: Make script executable
        run: chmod +x twitch.py

      # Run twitch.py to generate m3u8 file directly into channels directory
      - name: Update .m3u8 files
        run: python twitch.py livethess > channels/thessalia.m3u8

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "GitHub Actions"

      # Commit and push changes
      - name: Commit and push changes
        run: |
          cd channels
          git init
          git add .
          git commit -m "Update thessalia.m3u8 file"
          git push --force --quiet "https://${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/yourusername/channels.git" main
