name: Update Twitch Streams

on:
  schedule:
    - cron: '0 */4 * * *'  # Τρέχει κάθε 4 ώρες
  workflow_dispatch:

jobs:
  update_streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update .m3u8 files
        run: |
          python twitch.py livethess > ../../streams/thessalia.m3u8
          
      - name: Commit and push changes
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "GitHub Actions"
          git add ../../streams/*.m3u8
          git commit -m "Update .m3u8 files"
          git push
