name: grabbing streams

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1alt"
      
      - name: Grab m3u8 URLs
        id: grab_urls
        run: |
          cd ./core/platforms/
          python3 twitch.py livethess > /tmp/thessalia.m3u8  # Save temporary .m3u8 file
          cp /tmp/thessalia.m3u8 ../../streams/thessalia.m3u8  # Move .m3u8 file to streams directory

      - name: Clone target repository
        uses: actions/checkout@v2
        with:
          repository: <med1altd>/<channels>
          token: ${{ secrets.GH_TOKEN }}  # Ensure GH_TOKEN has repo permissions

      - name: Update .m3u8 file in target repository
        run: |
          mkdir -p ./streams
          cp ../../streams/thessaliatv.m3u8 ./streams/
          cd ./streams
          git add thessaliatv.m3u8
          git commit -m "Update .m3u8 file"
          git push origin HEAD:main
