name: Update Streams

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minute
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Generate m3u8 file
        run: |
          cd core/platforms/
          python3 twitch.py livethess > /tmp/thessaliatv.m3u8  # Generate .m3u8 file

      - name: Ensure streams directory exists
        run: mkdir -p ./streams

      - name: Copy m3u8 file to new-repo
        run: |
          cp /tmp/thessaliatv.m3u8 ./streams/thessaliatv.m3u8

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Commit and push changes to channels
        run: |
          cd ./streams
          git init
          git add .
          git commit -m "Update thassaliatv.m3u8"
          git push https://github.com/med1altd/channels.git HEAD:main
