name: grabbing streams

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Compile Java program
        run: |
          javac FetchAndDecodeHLS.java

      - name: Run Java program
        run: |
          java FetchAndDecodeHLS kqrw17iyoemx ../../../movies/tt22774688.m3u8

      - name: Configure Git
        run: |
          git config --global user.email "med1altdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../../../channels
          git add thessalia.m3u8
          git commit -m "streams updated"
          git push
