name: voe.sx

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout streams repository
        uses: actions/checkout@v2

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Navigate to channels repository
        run: cd channels/core/platforms/

      - name: Compile with Maven
        run: mvn clean package

      - name: Run Java program
        run: |
          java -cp target/fetch-and-decode-hls-1.0-SNAPSHOT.jar com.example.FetchAndDecodeHLS kqrw17iyoemx kqrw17iyoemx.m3u8
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
