name: Fetch and Decode HLS

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          architecture: x64

      - name: Compile and run Java program
        run: |
          cd streams/movies
          java -cp $GITHUB_WORKSPACE/channels/core/platforms/target/fetch-and-decode-hls-1.0-SNAPSHOT.jar FetchAndDecodeHLS kqrw17iyoemx
          
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit and push changes
        run: |
          git add kqrw17iyoemx.m3u8
          git commit -m "Update HLS file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
