name: Fetch and Decode HLS

on:
  workflow_dispatch:  # Manually trigger the workflow
    inputs:
      id_param:
        description: 'ID parameter for FetchAndDecodeHLS'
        required: true
        default: 'kqrw17iyoemx'  # Default value for ID parameter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          architecture: x64

      - name: Compile and run Java program
        run: |
          cd core/platforms
          javac FetchAndDecodeHLS.java
          java FetchAndDecodeHLS ${{ github.event.inputs.id_param }}
          
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.23-9/x64
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Commit and push changes
        run: |
          git checkout main  # Adjust branch name if necessary
          git add kqrw17iyoemx.m3u8
          git commit -m "Update HLS file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
