name: voe.sx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout streams repository
        uses: actions/checkout@v2

      - name: Download FetchAndDecodeHLS.java
        run: |
          mkdir -p channels/core/platforms
          curl -fsSL -o channels/core/platforms/FetchAndDecodeHLS.java https://github.com/med1altd/channels/raw/main/core/platforms/FetchAndDecodeHLS.java

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile and run Java program
        run: |
          cd channels/core/platforms
          javac FetchAndDecodeHLS.java
          java FetchAndDecodeHLS kqrw17iyoemx kqrw17iyoemx.m3u8
          cp kqrw17iyoemx.m3u8 ../../../streams/movies/

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Commit and push changes
        run: |
          cd ../../../streams/movies
          git add kqrw17iyoemx.m3u8
          git commit -m "Update HLS file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
