name: voe.sx

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout private repository
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          git clone https://med1altd:${{ secrets.PRIVATE_REPO_PAT }}@github.com/med1altd/channels.git private-repo

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Specify the distribution to use
          java-version: '11'
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: true

      - name: Compile Java program
        run: |
          cd private-repo
          javac FetchAndDecodeHLS.java

      - name: Run Java program
        run: |
          cd private-repo
          java FetchAndDecodeHLS kqrw17iyoemx

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ../../../movies
          git add kqrw17iyoemx.m3u8
          git commit -m "movies streams updated"
          git push
