name: Fetch and Decode HLS

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: Create movies directory
        run: mkdir -p streams/movies

      - name: Run Python script to fetch HLS URL
        working-directory: streams/movies
        run: |
          python3 ../../private-repo/core/platforms/FetchAndDecodeHLS.py kqrw17iyoemx > tt22774688.m3u8 2>&1
          cat tt22774688.m3u8  # Print output for debugging

      - name: Print Python version
        run: python --version

      - name: Print environment variables
        run: env

      - name: Commit and push changes
        run: |
          git -C private-repo add .
          git -C private-repo commit -m "Update streams"
          git -C private-repo push
