name: twitch

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"

      - name: checkout private repository
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          git clone https://med1altd:${{ secrets.PRIVATE_REPO_PAT }}@github.com/med1altd/channels.git private-repo

      - name: grab m3u files
        run: |
            pwd
            cd private-repo/core/platforms/
            python3 twitch.py livethess > ../../../channels/thessalia.m3u8
            python3 twitch.py eurotvgr > ../../../channels/eurotv.m3u8
            python3 twitch.py flashtvgr > ../../../channels/flashtv.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "streams updated"
          git push
