name: voe.sx

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout channels repository
        uses: actions/checkout@v2
        with:
          repository: med1altd/channels
          token: ${{ secrets.PRIVATE_REPO_PAT }}

      - name: Set up JDK 11 and Maven
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
          architecture: x64

      - name: Navigate to core/platforms directory
        run: cd channels/core/platforms/
        
      - name: Compile and run Java program
        run: |
          javac FetchAndDecodeHLS.java
          java FetchAndDecodeHLS kqrw17iyoemx kqrw17iyoemx.m3u8
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
