name: twitch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "medialtdcontact@gmail.com"
          git config --global user.name "med1altd"

      - name: Checkout private repository
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          git clone https://med1altd:${{ secrets.PRIVATE_REPO_PAT }}@github.com/med1altd/channels.git private-repo

      - name: Grab m3u files
        run: |
            cd private-repo/core/platforms/
            python3 twitch.py livethess > ../../../channels/thessalia.m3u8
            python3 twitch.py eurotvgr > ../../../channels/eurotv.m3u8
            python3 twitch.py flashtvgr > ../../../channels/flashtv.m3u8

      - name: Add changes to git
        run: |
          cd private-repo
          git add -A
          ls -la 
          
      - name: Commit and push changes
        run: |
          cd private-repo
          git commit -m "streams updated"
          git push origin main
