name: voe.sx

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout streams repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Clone private repository
        env:
          PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}
        run: |
          git clone https://med1altd:${{ secrets.PRIVATE_REPO_PAT }}@github.com/med1altd/channels.git private-repo

      - name: Run Python script to grab m3u files
        working-directory: private-repo/core/platforms
        run: |
          python3 FetchAndDecodeHLS.py kqrw17iyoemx > ../../../streams/movies/tt22774688.m3u8

      - name: Commit and push changes
        run: |
          cd ..
          git add -A
          git commit -m "Update streams"
          git push
