name: voe.sx

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PRIVATE_REPO_PAT: ${{ secrets.PRIVATE_REPO_PAT }}

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Create directory structure
        run: mkdir -p channels/core/platforms

      - name: Download FetchAndDecodeHLS.java from private repository
        run: |
          curl -fsSL -o channels/core/platforms/FetchAndDecodeHLS.java \
            -H "Authorization: token $PRIVATE_REPO_PAT" \
            https://raw.githubusercontent.com/med1altd/channels/main/core/platforms/FetchAndDecodeHLS.java

      - name: Display fetched file
        run: cat channels/core/platforms/FetchAndDecodeHLS.java

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Compile and run Java program
        run: |
          cd channels/core/platforms
          javac FetchAndDecodeHLS.java
          java FetchAndDecodeHLS kqrw17iyoemx kqrw17iyoemx.m3u8
          cp kqrw17iyoemx.m3u8 ../../../streams/movies/
